name: demo-self-hosted

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, youtube, demote]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Corriendo en runner self-hosted de AWS"