name: Demo AWS Ephemeral Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, demo, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test execution
        run: echo "¡Instancia EC2 desplegada correctamente!"